// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4461.RobotBuilderTest;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveBaseLeftFront;
    public static SpeedController driveBaseRightFront;
    public static SpeedController driveBaseleftBack;
    public static SpeedController driveBaseRightBack;
    public static RobotDrive driveBaseRobotDrive41;
    public static DoubleSolenoid pneumaticsArm;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBaseLeftFront = new Victor(4);
        LiveWindow.addActuator("DriveBase", "LeftFront", (Victor) driveBaseLeftFront);
        
        driveBaseRightFront = new Victor(1);
        LiveWindow.addActuator("DriveBase", "RightFront", (Victor) driveBaseRightFront);
        
        driveBaseleftBack = new Victor(3);
        LiveWindow.addActuator("DriveBase", "leftBack", (Victor) driveBaseleftBack);
        
        driveBaseRightBack = new Victor(2);
        LiveWindow.addActuator("DriveBase", "RightBack", (Victor) driveBaseRightBack);
        
        driveBaseRobotDrive41 = new RobotDrive(driveBaseLeftFront, driveBaseleftBack,
              driveBaseRightFront, driveBaseRightBack);
        
        driveBaseRobotDrive41.setSafetyEnabled(true);
        driveBaseRobotDrive41.setExpiration(0.1);
        driveBaseRobotDrive41.setSensitivity(0.5);
        driveBaseRobotDrive41.setMaxOutput(1.0);

        pneumaticsArm = new DoubleSolenoid(2, 2, 1);      
        LiveWindow.addActuator("Pneumatics", "Arm", pneumaticsArm);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
